### ISSUE TITLE
Handle unserializable component state generically

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#101]
"Circular structure" error when dealing with jQuery

> Thanks for taking care of this guys. It almost works except when I wrap my $el in a jquery object like this $($el). Sorry if I'm doing funny things with my Alpine setup! 😆
> 
> https://codepen.io/pomartel/pen/abmbyNg

I wonder if it's going to be possible to manage all the weird situations like this one. Maybe just wrap it in a try catch and display it as an "Unknown Element"?

_Originally posted by @pomartel in https://github.com/alpine-collective/alpinejs-devtools/issues/78#issuecomment-738045467_

We can add a check that each field's value is serializable and label it as unserializable if not.

I'll create an "enhancement" piece to add some UI that points the user to create an issue/discussion on the devtools repo when they see that so that we can decide if it's something we want to handle, eg. we might want to unfurl jQuery but not worry about a ton of other generic bugs.

**Comment by pomartel** [comment]
Thanks Hugo! That looks good to me. I will test it out once 0.0.9 gets released.

**Comment by HugoDF** [comment]
> Thanks Hugo! That looks good to me. I will test it out once 0.0.9 gets released.

0.0.9 is live for Firefox, pending review for Chrome 👍 

Thanks for suggesting to handle these types of issues in a generic fashion.

**Comment by pomartel** [comment]
Works great now. Thanks a lot for the quick fix!
