### ISSUE TITLE
The components are not updated after an Ajax request

### ISSUE THREAD

**Issue by pomartel** [alpine-collective/alpinejs-devtools#104]
When components are added or removed on page with AJAX, the devtools node list is not updated accordingly. Closing and reopening the devtools does refresh and update the list.

**Comment by HugoDF** [comment]
As discussed on the Alpine Discord, the solution here is to provide a way for the user to ask for the components/component data to be refreshed, I think we had a commented out "refresh" icon in the panel.html:

https://github.com/alpine-collective/alpinejs-devtools/blob/b06d883a4e25872e84a93de8c8777be08abd2c7d/packages/shell-chrome/assets/panel.html#L82-L84

if we bring that back and on click we'll need to:
1. send a message from the panel to the backend (probably with a new method in state.js that we can call), that method will ping a message with name "load-components" or similar
2. receive the message in backend.js, see `handleMessages`, to handle the message, remove existing observers, remove the overlay (if it exists) and re-initialize the backend (using `startAlpineBackend`)
