### ISSUE TITLE
Upgrade to Tailwind v2 + re-assess use of Tailwind UI

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#114]
We should upgrade to Tailwind v2, note that there are some changes to how purge works and also to some classes https://tailwindcss.com/docs/upgrading-to-v2.

We should also look at whether or not Tailwind UI classes are used and remove the npm package if it's not used. If it is used, we'll need to upgrade as well to match Tailwind v2.

**Comment by stephenoldham** [comment]
Yeah, the upgrade is a straight forward process. Not sure we will need Tailwind UI but will double check. Happy to sort this.

**Comment by HugoDF** [comment]
> Yeah, the upgrade is a straight forward process. Not sure we will need Tailwind UI but will double check. Happy to sort this.

Cool, go for it

I think we do use some of the classes they've renamed and we have a warning about purging but I don't think it makes a difference (as far as I understand we don't manually add utility classes)
