### ISSUE TITLE
UI to surface Alpine.js eval errors

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#126]
Alpine.js uses `console.warn` in the following scenarios:

1. ~~x-if/x-for on a non-`template` https://github.com/alpinejs/alpine/blob/ee019cbc66d2adb3e5126bf3822d9d701a40daf8/src/utils.js#L29~~ #141 
2. ~~`template` with more than 1 child node https://github.com/alpinejs/alpine/blob/ee019cbc66d2adb3e5126bf3822d9d701a40daf8/src/utils.js#L31~~ #141 
3. error during expression evaluation https://github.com/alpinejs/alpine/blob/5cc46c31b08e4b25821fb85fd0fad6903bc7e574/src/utils.js#L69

I believe some developers suppress `console.warn`, it would be nice to surface the relevant errors/warnings:
- in a "warnings" tab in the devtools 
- highlight the offending components/elements (toggleable through settings)

~~For 1. and 2. we should probably re-scan the DOM and to figure out which are the offending `template`'s.~~ Moved to a separate issue to have additional structural checks #141 

For 3. the `console.warn` contains the element as well as the expression.

**Comment by KevinBatdorf** [comment]
Any idea where we should add various tabs? We could remove the "Alpine v2.7.1 detected" and add them there. Just a quick idea:

<img width="1567" alt="Screen Shot 2020-12-16 at 1 46 11 PM" src="https://user-images.githubusercontent.com/1478421/102314482-1c301900-3fa5-11eb-9e71-d2863c963953.png">

```html
<div class="inline-flex space-x-2 text-md">
  <div><button class="bg-alpine-300 hover:bg-alpine-300 leading-none px-3 py-2 rounded-full">Components</button></div>
  <div><button class="hover:bg-alpine-300 leading-none px-3 py-2 rounded-full">Events</button></div>
  <div><button class="hover:bg-alpine-300 leading-none px-3 py-2 rounded-full">Warnings</button></div>
</div>
```

We could also add a count for each button when not selected, like "Warnings <small>2</small>" Or grab something from tailwindui?

I also noticed a white gap bottom right of the right pane. I'll see what that is later

**Comment by HugoDF** [comment]
We could do tabs like you've done but to the right, before the GitHub/docs/settings icons?

**Comment by KevinBatdorf** [comment]
Here's how that looks:

<img width="1567" alt="Screen Shot 2020-12-16 at 4 24 24 PM" src="https://user-images.githubusercontent.com/1478421/102329639-3674f180-3fbb-11eb-818f-62ac29e74d87.png">

It could be moved over some more too. The "docs" icon has some extra padding too that should probably be removed to match the other icons.

Is it just me or does the "Alpine.js v2.7.3 detected" feel too overwhelming? It's not really that critical of information besides the version number, which is really only critical in a situation where you're trying to debug in support

**Comment by KevinBatdorf** [comment]
Also, i'm not a great designer, so if someone has an opinion on the button styles, etc. please do share it. :)

**Comment by ryangjchandler** [comment]
I went with the right aligned tabs (not pill shapes though) in #129 (still a WIP). Probably makes more sense, I tend to naturally float to the right when searching for buttons.

**Comment by HugoDF** [comment]
Yeah maybe we can shorten the text from "Alpine.js v2.7.3 detected" to circle icon + "v2.7.3" and maybe use a lighter shade of orange?

We can also compress the pills/tabs for small breakpoints by switching to an icon + title attribute

**Comment by KevinBatdorf** [comment]
Ah, I didn't check #​129 yet. All that sounds good. Right side sounds good too. Choosing the right icons might be the challenge now :)

I think we also need room for a counter too. For example if there are 3 warnings or 5 events. Or if not a counter, just a colored dot might be enough to show there's some activity there.

<img width="1567" alt="Screen Shot 2020-12-16 at 5 15 26 PM" src="https://user-images.githubusercontent.com/1478421/102335330-50660280-3fc2-11eb-82a1-4047f1d393fd.png">

**Comment by KevinBatdorf** [comment]
We also need a loading state for the buttons. Or otherwise just make the toolbar always dark?

<img width="1567" alt="Screen Shot 2020-12-16 at 5 17 00 PM" src="https://user-images.githubusercontent.com/1478421/102335550-a6d34100-3fc2-11eb-9eb2-dd41778f0c7d.png">

**Comment by HugoDF** [comment]
> We also need a loading state for the buttons. Or otherwise just make the toolbar always dark?
> 
> <img alt="Screen Shot 2020-12-16 at 5 17 00 PM" width="1567" src="https://user-images.githubusercontent.com/1478421/102335550-a6d34100-3fc2-11eb-9eb2-dd41778f0c7d.png">

yeah I think this looks fine, we can disable/fade or even hide them while loading

**Comment by stephenoldham** [comment]
Not to put the cat amongst the pigeons 😉

Here's my take:

![AlpineDevTools_Concept](https://user-images.githubusercontent.com/2156070/102503825-07708580-4078-11eb-9d68-6b7d276bf0cb.png)


- The right align feels right for the top nav items
- Might be worth separating the secondary nav items to give a bit of visual/UX hierarchy
- Not wanting to just go ahead and copy the VueJs guys, but an active tab being underlined in some way when it's in a header I reckon feels a bit cleaner
- Also not wanting to completely rip off @KevinBatdorf 😉, but I really like the footer in his inline Alpine inspector tool*. Could be a better place to put version detection being mindful that the top bar is going to fill up pretty quick when using the panel in the sidebar view. Could also become a kind of live console e.g. seeing events come in if you're not currently in the events panel 'Click event caught from blah component` etc.

* Don't get me started on those sweeeet looking themes 👌🏼😍

**Comment by stephenoldham** [comment]
Or does the right align feel right?! 😬😆

![AlpineDevTools_Concept_v2](https://user-images.githubusercontent.com/2156070/102505680-312aac00-407a-11eb-9870-15475aca5b58.png)

**Comment by KevinBatdorf** [comment]
I like it! And rip off anything :) 

Maybe we can add a theming setup to this project eventually as well. 

Looking at both, right-aligned seems nicer. Maybe we could move those three icons to the right footer as well.

**Comment by ryangjchandler** [comment]
I personally prefer the right aligned items, feels less crowded on the left hand side where the list of components, etc will be.

@stephenoldham is the design master mind though ;)

**Comment by stephenoldham** [comment]
Ha! Not sure about that @ryangjchandler 😆

Big yes from me on the theming setup @KevinBatdorf 👍🏼 Would be a rad addition to the settings layer.

The only concern might be the settings getting lost on the footer but see what you think:

![AlpineDevTools_Concept_v1 1](https://user-images.githubusercontent.com/2156070/102511422-ab5e2f00-4080-11eb-90b5-8046b9837d08.png)

Here's a few footer vibes...you get the idea:

<img width="400" alt="Screenshot 2020-12-17 at 15 57 58" src="https://user-images.githubusercontent.com/2156070/102511543-d5175600-4080-11eb-9256-5d42d9bb879d.png">
<img width="424" alt="Screenshot 2020-12-17 at 15 57 41" src="https://user-images.githubusercontent.com/2156070/102511551-d6488300-4080-11eb-969e-7de295bca2d6.png">
<img width="376" alt="Screenshot 2020-12-17 at 15 57 34" src="https://user-images.githubusercontent.com/2156070/102511557-d6e11980-4080-11eb-9d43-aaa9584ed73f.png">
<img width="370" alt="Screenshot 2020-12-17 at 15 56 59" src="https://user-images.githubusercontent.com/2156070/102511560-d779b000-4080-11eb-8217-e40228355767.png">

**Comment by ryangjchandler** [comment]
The 2nd one in is my favourite. The separator is nice, but I also like the last one with the different BG colour.

**Comment by ryangjchandler** [comment]
If somebody is going to implement the tabs, etc, I'll hold off on #129.

**Comment by HugoDF** [comment]
> Ha! Not sure about that @ryangjchandler 😆
> 
> Big yes from me on the theming setup @KevinBatdorf 👍🏼 Would be a rad addition to the settings layer.
> 
> The only concern might be the settings getting lost on the footer but see what you think:
> 
> ![AlpineDevTools_Concept_v1 1](https://user-images.githubusercontent.com/2156070/102511422-ab5e2f00-4080-11eb-90b5-8046b9837d08.png)
> 
> Here's a few footer vibes...you get the idea:
> 
> <img alt="Screenshot 2020-12-17 at 15 57 58" width="400" src="https://user-images.githubusercontent.com/2156070/102511543-d5175600-4080-11eb-9256-5d42d9bb879d.png">
> 
> <img alt="Screenshot 2020-12-17 at 15 57 41" width="424" src="https://user-images.githubusercontent.com/2156070/102511551-d6488300-4080-11eb-969e-7de295bca2d6.png">
> 
> <img alt="Screenshot 2020-12-17 at 15 57 34" width="376" src="https://user-images.githubusercontent.com/2156070/102511557-d6e11980-4080-11eb-9d43-aaa9584ed73f.png">
> 
> <img alt="Screenshot 2020-12-17 at 15 56 59" width="370" src="https://user-images.githubusercontent.com/2156070/102511560-d779b000-4080-11eb-8217-e40228355767.png">

😍 could try with the status bar (Alpine.js vX.X.X detected) between the header and the main panes?

I was happy to settle for text links in the header 😄

**Comment by stephenoldham** [comment]
Right then...the contenders...

![AlpineDevTools_Concept_v1 2](https://user-images.githubusercontent.com/2156070/102516093-663cfb80-4086-11eb-82a4-d2758afce59b.png)
![AlpineDevTools_Concept_v2](https://user-images.githubusercontent.com/2156070/102516095-66d59200-4086-11eb-905e-04df44f0a6fe.png)

Quite like both 😆 Subheader version would just need a bit of play with the padding on the right. Thoughts?

**Comment by HugoDF** [comment]
Subheader version will give use the opportunity to bring in a search UI maybe?

I guess they're very similar either way (plus I'm sure we can move it around if we decide on one and end up not liking it)

**Comment by ryangjchandler** [comment]
I'm gonna vote for the footer version.

**Comment by stephenoldham** [comment]
I think in terms of the content hierarchy I prefer the footer. Also feels like there's more space in that layout with less at the top.

@HugoDF As you said we can totally change it if we don't vibe that layout in practise.

**Comment by HugoDF** [comment]
Yeah it's fine, I'm a bit weary of making big changes to the layout of the UI if people have come to rely on it.

Then again, better to make the change now and support future features rather than wait

**Comment by ryangjchandler** [comment]
Anybody volunteering to implement the new design?

**Comment by stephenoldham** [comment]
Can do 👍🏼

**Comment by HugoDF** [comment]
cool, I would say just to watch out for the `testid`'s otherwise tests will fail and also to hide tabs that don't have any content for production builds (the same way we hid the settings modal #111)

**Comment by HugoDF** [comment]
Additional things we can write our own "warning" for (see https://github.com/alpinejs/alpine/discussions/975)

- `x-init` on an element without `x-data`
- Alpine is loaded but there is no `x-data` on the page
- an alpine directive is being used on an element that doesn't have x-data and has no element with `x-data` in its ancestors

Thinking about it further the following:

- x-if/x-for on a non-template element
- template with more than 1 child node 

Don't need to/can't be done with `console.warn` interception, so it might be worth splitting as a separate issue.

Other note: I'm not sure how we're going to highlight `template`'s that have issues (since they don't visually display)

**Comment by HugoDF** [comment]
We might not need to instrument `console.warn` once https://github.com/alpinejs/alpine/pull/1000 gets released
