### ISSUE TITLE
$parent.$parent not defined

### ISSUE THREAD

**Issue by markfirmware** [alpine-collective/alpinejs-devtools#139]
See https://github.com/markfirmware/audit/blob/efb45657ce91a7368b5a8a6cf7364bff60e9e815/docs/index.html#L13-L16

These lines detect the completion of four digits and then attempt to change the state of the fsm.

Before moving on to a better design, is chaining back more than one frame supported by $parent?

**Comment by KevinBatdorf** [comment]
Hi,

If you're using the `$parent` helper, you can't use `$parent.$parent` at all, but instead can use `$component(id)`. 

However, I think the devtools doesn't pick up changes made via `$component`/`$parent` yet but I'll look into that this weekend (just noticed this yesterday actually)

**Comment by KevinBatdorf** [comment]
Unrelated, but I wrote a pin type component awhile back you might find useful.

https://codepen.io/KevinBatdorf/pen/Vweprqg

**Comment by markfirmware** [comment]
Thanks. I will close this and study your pin component. I see it uses tick which is on my list.
