### ISSUE TITLE
Chrome Web Store warning

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#147]
Received the following from Chrome Web Store.

```
We wanted to let you know that your item is at risk of being removed from the Chrome Web Store. Please find the details below.

Violation: Requesting but not using the following permission(s):
contextMenus
storage
How to rectify: Remove the above permission(s)

...

Please make the necessary changes within 14 days in order to avoid removal.
```

We need to remove `contextMenus` and `storage` permissions since we're not using them 👍.

Should give us a chance to roll out the redesign as well.

**Comment by KevinBatdorf** [comment]
Fair enough! I guess we don't need contextMenus, right?

Might not be able to do the storage stuff until this weekend so maybe better to remove it for now?

**Comment by HugoDF** [comment]
> Fair enough! I guess we don't need contextMenus, right?
> 
> Might not be able to do the storage stuff until this weekend so maybe better to remove it for now?
> 
> edit: They say 14 days, but not sure we should wait if we don't have to.

Yep, let's remove both and re-add as part of the PR that uses it 👍👍
