### ISSUE TITLE
x-model issue

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#151]
Reported over email

> I noticed that Alpine Tools in not reflecting changes made in the DOM to inputs with x-model assigned to them.
> 
> I have tested in latest versions of Firefox and Brave on macOS 10.15.7
> 
> If I use x-text or x-html in the page, then that does work and values stay synced.

I've asked for a reproduction but the reporter hasn't got back to me, putting this in an issue, will close if no one has seen this before and reproduction steps can't be found.

**Comment by KevinBatdorf** [comment]
I've noticed a few times updates not happening with `$component`. I'll try to go back and see if it's related to `x-model`

**Comment by ajitbohra** [comment]
have experienced similar recently, will get reproduction repo. 

here updated values are not reflected in devtools
https://bf-compare.netlify.app/

**Comment by HugoDF** [comment]
Thanks @ajitbohra we don't necessarily need the repo since you've posted a publicly accessible app 👍👍👍

**Comment by metametadata** [comment]
macOS Firefox 151.0.4, alpinejs-devtools 2.7.4.

Reproducible in the example from https://github.com/alpine-collective/alpinejs-devtools/issues/165#issuecomment-1038456227: 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/alpinejs" defer></script>
  </head>
  <body x-data="{}">
    <section x-data="{ alternatives: [''] }">
      <div>
        <form>
          <template x-for="(alternative, index) in alternatives">
            <div class="flex">
              <input type="text" x-model="alternatives[index]">
              <button type="button" @click="alternatives.splice(index, 1)" class="btn btn-blue">-</button>
            </div>
          </template>
          <button type="button" @click="alternatives.push('')" class="btn btn-blue self-start">+</button>
        </form>
      </div>
    </section>
  </body>
</html>
```

## Steps:

1) Open the page.
2) Open the devtools. Navigate to section -> alternatives. You should see `0: ""` inside, as expected.
3) Change the input value to `123`. Observe the devtools.

## Expected

`0: "123"`

## Actual 

No changes, still `0: ""`.
