### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#154]
https://developer.apple.com/documentation/safariservices/safari_web_extensions

@ryangjchandler mentioned that Safari implements the web extension API, from what I've seen on Twitter, it looks like it implements the `chrome.*` APIs (same as what Firefox does).

Outstanding questions:
- how would the release process look like (looks like there's an xcode CLI tool)?
- do we need an Apple Developer license? (I think I've got one kicking around since I've got a client iOS app listed on the App Store)

**Comment by KevinBatdorf** [comment]
How about Edge?

**Comment by HugoDF** [comment]
> How about Edge?

Interesting, Edge is Chromium based, should be even more seamless https://docs.microsoft.com/en-gb/microsoft-edge/extensions-chromium/#publishing-to-the-microsoft-edge-add-ons-website

**Comment by ryangjchandler** [comment]
Okay, bit of a blocker here. Safari supports some of the `chrome.*` and `browser.*` APIs, but we wouldn't be able to do much with this extension because it doesn't support the `chrome.devtools` stuff, meaning we can't create custom panels, etc.

**Comment by HugoDF** [comment]
Ok if Safari is blocked, we should probably split out a separate Edge support issue 😄

**Comment by jakback** [comment]
👍 Since Safari seems to be the new Internet Explorer, I'm developing there first. Hope they speed things up a little.

**Comment by HugoDF** [comment]
> 👍 Since Safari seems to be the new Internet Explorer, I'm developing there first. Hope they speed things up a little.

Hey, I don't think it's going to be possible to add Safari support short term since they don't implement the devtools API.

**Comment by crstnre** [comment]
Hey, that's the issue here. No worries, I blame Apple for that, not you. 🙂

**Comment by HugoDF** [comment]
Closing because I don't think we could do this right now.

We can revisit when Safari has 1-1 support for the APIs we use.

**Comment by camilleterol** [comment]
With the new APIs announced at the WWDC, I think that this issue is no longer blocked.

https://developer.apple.com/wwdc22/10100

**Comment by camilleterol** [comment]
Can we remove the blocked label, and reopen it? I'd be more than happy to start working on making it work on Safari
