### ISSUE TITLE
Remove call to npm

### ISSUE THREAD

**Issue by KevinBatdorf** [alpine-collective/alpinejs-devtools#158]
This never works for me when developing locally (I get CORS errors) and I think we can move this sort of functionality out of the main plugin and into the errors pane logic when that gets implemented. 

https://github.com/alpine-collective/alpinejs-devtools/blob/master/packages/shell-chrome/src/devtools/devtools.js#L89

**Comment by HugoDF** [comment]
Does this happen in the simulator only or also when using through browser devtools?

**Comment by KevinBatdorf** [comment]
Yeah I guess it's another simulator-only issue. 

Is the intent of that feature to just inform the user they are using an older version? If so then it makes sense to abstract that to a warnings tab anyway since using an older version of Alpine isn't necessarily an error. It could be intentional (especially when v3 comes out)

**Comment by HugoDF** [comment]
> Yeah I guess it's another simulator-only issue. 
> 
> Is the intent of that feature to just inform the user they are using an older version? If so then it makes sense to abstract that to a warnings tab anyway since using an older version of Alpine isn't necessarily an error. It could be intentional (especially when v3 comes out)

Yeah that makes sense maybe we rename the issue to reflex that?

The version stuff is in the footer at the moment.

**Comment by HugoDF** [comment]
@KevinBatdorf I guess we can check whether this works or not, websites with 2.8.0 should have the "outdated" version display even though we haven't bumped the alpine version in the devtools

**Comment by KevinBatdorf** [comment]
Seems buggy. Here's what I noticed:

![Screen Shot 2021-02-24 at 7 45 59 AM](https://user-images.githubusercontent.com/1478421/109002542-f2981a00-76d8-11eb-8e47-acc2e9f4946a.png)

1. It initially showed the orange dot and hovering over the text, the title said 2.8.1 was the latest
2. I pressed it and it tried to load a page inside the devtools but failed to load
3. I closed and re-opened, but this time it told me 2.8.0 was the latest version

![Screen Shot 2021-02-24 at 7 45 21 AM](https://user-images.githubusercontent.com/1478421/109002632-0a6f9e00-76d9-11eb-9c94-a7d98d4a063f.png)

**Comment by HugoDF** [comment]
> Seems buggy. Here's what I noticed:
> 
> ![Screen Shot 2021-02-24 at 7 45 59 AM](https://user-images.githubusercontent.com/1478421/109002542-f2981a00-76d8-11eb-8e47-acc2e9f4946a.png)
> 
> 1. It initially showed the orange dot and hovering over the text, the title said 2.8.1 was the latest
> 2. I pressed it and it tried to load a page inside the devtools but failed to load
> 3. I closed and re-opened, but this time it told me 2.8.0 was the latest version
> 
> ![Screen Shot 2021-02-24 at 7 45 21 AM](https://user-images.githubusercontent.com/1478421/109002632-0a6f9e00-76d9-11eb-9c94-a7d98d4a063f.png)
> 

Yeah the the latter sounds like it timed out, which is what we want, if the user is on devtools latest, the bundled Alpine version will tend to be latest too.

**Comment by HugoDF** [comment]
Seems to work as expected, if you go to https://codewithhugo.com/search/ and open the devtools, on hover it shows the right version because it fetched it from npm

<img width="501" alt="Screenshot 2021-03-06 at 19 49 27" src="https://user-images.githubusercontent.com/6459679/110219103-1582b500-7eb5-11eb-9a98-02595e431ece.png">

I'll close this for now. We could make it so that it doesn't make the call on localdev?
