### ISSUE TITLE
Improve loading of components with lots of data

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#179]
#174 / #177 fixes the load time of the devtools. This means we've closed #10 but we still get performance issues, localised to loading of component data.

This is an umbrella issue for 2 things we're seeing after the above, for components with large `$data` eg. https://alpinetoolbox.com, the main "div" component:

1. loading the component data can take a while ("get-data", "set-data")
2. toggling attributes is sluggish

We still need to pinpoint where exactly the bottlenecks are, candidates:

- preparing of the data for serialization (we traverse the data and generate a data structure for the panel)
- `JSON.stringify` (the actual serialization might be costly for whatever reason)
- sending a large string from the `backend` to the `proxy` to the `app` to `state` to the `devtools` (panel)
- rendering the data in the panel with Alpine

Current ideas to fix bottlenecks (depending on where they are):

- the stringification/serialization and parse/deserialization operations might be costly -> switch to a faster implementation, probably a library
- making serialization an async process so it yields the event loop for execution of other operations (would keep the page/devtools more interactive)
- reduce the size of the message by
  - changing the schema (eg. removing unused fields)
  - encoding it (Lempel Ziv? encoding performance would have to be weighed against the cost of a larger payload)
- Alpine.js rendering optimisations, eg. `x-show` vs `x-if`, adding `key` to `x-for`'s

### Notes 

Ryan found this for profiling extensions  https://gist.github.com/bvaughn/ab6a6aefcda21dd2db69c7eaa7bf3332

It's probably worth adding a "load test"/"benchmark" Cypress example based on alpinetoolbox.com data.

**Comment by KevinBatdorf** [comment]
Could we keep track of the component state and only send the diff across? So if the user only updates one property we wont send over the entire data object.

If I remember correctly, the front to back communication is a bit segmented right now, right? Would it be good to refactor it to have everything handled through a single place? (I might be wrong about that. I just remember it being non-trivial trying to wrap my head around how the communication works)

**Comment by HugoDF** [comment]
Hmmm the diff wouldn't solve the first load.

And yes, the idea is to refactor now that we've got a test suite that covers the features. There's a whole bunch of "flattening"/data mapping that might be redundant and having a "state" instance to keep track of message values and then syncing that to the panel x-data might well end up being overkill as well.

**Comment by KevinBatdorf** [comment]
Initial load could iterate over the components one by one using promises instead of initializing everything at once. The UI could update one by one as well so users don't have to wait for the loading screen to finish. 

So maybe the initial payload sends over a blueprint of all the components, then each component is handled one by one? Does that make sense?

**Comment by HugoDF** [comment]
> Initial load could iterate over the components one by one using promises instead of initializing everything at once. The UI could update one by one as well so users don't have to wait for the loading screen to finish. 
> 
> So maybe the initial payload sends over a blueprint of all the components, then each component is handled one by one? Does that make sense?

Oh right, I've changed the messaging (in that messaging PR) so that on page load we only look to load up the "components list" (left pane of components tab), we only go to read the component data when the user selects a component.

We still hit an issue if a component has a ton of data (like alpine toolbox homepage with ~140 array elements)

**Comment by KevinBatdorf** [comment]
i spent the last hour looking around and I suspect the bottleneck is just Alpine's `x-for` rendering. I think to solve it we will have to write our own insertion instead of using Alpine. 

Sometimes it took 10+ seconds for me on Alpine Toolbox

**Comment by ryangjchandler** [comment]
> i spent the last hour looking around and I suspect the bottleneck is just Alpine's `x-for` rendering. I think to solve it we will have to write our own insertion instead of using Alpine.
> 
> Sometimes it took 10+ seconds for me on Alpine Toolbox

Hm, I wonder what in particular is slowing down the `x-for`. I guess it's the event listeners, etc being bound to the dynamic elements..

**Comment by KevinBatdorf** [comment]
yeah and there's thousands of nodes being inserted in the case of alpinetoolbox. I might have a simple tweak though to improve it . Getting 3 second load times now instead of 10

**Comment by ryangjchandler** [comment]
> yeah and there's thousands of nodes being inserted in the case of alpinetoolbox. I might have a simple tweak though to improve it . Getting 3 second load times now instead of 10

👀

**Comment by KevinBatdorf** [comment]
Left two potential optimizations here that i don't think affect anything negatively but greatly improve responsiveness in my testing. 

https://github.com/alpine-collective/alpinejs-devtools/pull/177#discussion_r593522339

**Comment by HugoDF** [comment]
> Left two potential optimizations here that i don't think affect anything negatively but greatly improve responsiveness in my testing. 
> 
> https://github.com/alpine-collective/alpinejs-devtools/pull/177#discussion_r593522339
> 

Nice! I think let's merge that PR since it's already doing a bunch of stuff (mostly not in the Alpine template side) and we can start fixing the data rendering pane perf in separate PRs

**Comment by HugoDF** [comment]
> i spent the last hour looking around and I suspect the bottleneck is just Alpine's `x-for` rendering. I think to solve it we will have to write our own insertion instead of using Alpine. 

Depending on what's slow in the x-for we could switch to x-html + building the template as a JS string.

**Comment by HugoDF** [comment]
Suggestion from Ryan to patch `updateElements` and notify the extension that a component is being rerendered

**Comment by KevinBatdorf** [comment]
> Suggestion from Ryan to patch `updateElements` and notify the extension that a component is being rerendered

Is this significantly faster? Could we do this if the devtools are already open and the user does a page refresh?

**Comment by HugoDF** [comment]
> > Suggestion from Ryan to patch `updateElements` and notify the extension that a component is being rerendered
> 
> Is this significantly faster? Could we do this if the devtools are already open and the user does a page refresh? 

It all depends on where/why we're slow.

I don't think the mutation observer is necessarily that slow.

Simplifying the "set-data" payload will help with readability but it also stands to reason that sending less data/doing less work will improve performance.

**Comment by HugoDF** [comment]
By the way @KevinBatdorf I'm tempted to close this, the idea to replace a couple of `x-show`'s with `x-if` seems to have done the trick.

The remaining delay is acceptable I think (plus I don't think that many people were hitting even that limitation before otherwise we would probably have seen more issues about that).

**Comment by KevinBatdorf** [comment]
Yeah I agree we're pretty good for now.
