### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by aguillen-js** [alpine-collective/alpinejs-devtools#253]
Alpine Devtools throws an error as shown in the image even though Alpine is defined in the global window object.

Alpine in being included via a script tag using the defer attribute.

![Screenshot 2021-06-27 232346](https://user-images.githubusercontent.com/5055390/123575077-00e96600-d79f-11eb-9e54-be865c3d8e14.png)

**Comment by HugoDF** [comment]
Interesting

If I remember correctly the devtools should wait until `window.Alpine` is defined before injecting the backend.

Have you got a specific page where this happens?

**Comment by aguillen-js** [comment]
@HugoDF I am using Alpine on a custom WordPress admin page. I discovered something interesting after the error suddenly disappeared: the error only appears if the Chrome developer tools are open on every page reload. If I close the Chrome developer tools, reload the page and reopen them, the error does not appear.

**Comment by HugoDF** [comment]
Thanks for that

Does it happen on the sites that use v2?

I'm wondering if there's a slight difference in recommended script loading causing the issue.

**Comment by aguillen-js** [comment]
@HugoDF Just checked! Everything works fine with v2 even on every page reload with the Chrome devtools open.

**Comment by HugoDF** [comment]
I'll be releasing devtools shortly, if you're able to keep reproducing on the latest version (once I release) feel free to reopen.

**Comment by aguillen-js** [comment]
@HugoDF Awesome! Thank you so very much!

**Comment by HugoDF** [comment]
It's out now, let me know if the issue is still around
