### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by slavatarsyurimi** [alpine-collective/alpinejs-devtools#289]
In certain situations my Google Chrome spits out the following error in the console:
```
    backend.js:236 Uncaught TypeError: Cannot read property '0' of undefined
    at AlpineDevtoolsBackend.getAlpineDataInstance (backend.js:236)
    at backend.js:355
    at Array.forEach (<anonymous>)
    at AlpineDevtoolsBackend.watchComponents (backend.js:354)
    at MutationObserver.<anonymous> (backend.js:497)
```

I have not been able to pinpoint an exact trigger yet. More often than not this means that there is a certain error in the Alpine component but sometimes the component itself seems to work just fine. After this error is thrown new data changes in the component are not registered anymore (or the whole component itself is not shown in the devtools at all if the error is econuntered at initialization). 
I am using Laravel Livewire and nested alpine v3 components (could be relevant?).

**Comment by tanthammar** [comment]
I am also getting this error all the time. It breaks multiple components for me. Have to disable the extension.

**Comment by HugoDF** [comment]
Do you have sample components? Or a web page I could look at?

**Comment by tanthammar** [comment]
@HugoDF I added a link in #295
