### ISSUE TITLE
header too tall

### ISSUE THREAD

**Issue by JeremyJaydan** [alpine-collective/alpinejs-devtools#290]
I like my devtools height to be about 1/3 of the window however that makes it a pain to use the alpine tab:

![image](https://user-images.githubusercontent.com/15324232/130236897-30e987be-2cb2-4e47-bbb6-77f3a18a029c.png)

Any chance it could be shorter? :)

perhaps like this:
![image](https://user-images.githubusercontent.com/15324232/130239427-26a86e33-23c0-4b64-8f70-329bcba3e2e8.png)

p.s. keep up the great work!

**Comment by stephenoldham** [comment]
Absolutely! Was actually originally like that, must've introduced a style issue at some point. Will sort 👍🏼
