### ISSUE TITLE
alpine devtools fails when x-data is on a <form> element

### ISSUE THREAD

**Issue by JeremyJaydan** [alpine-collective/alpinejs-devtools#292]
I encountered the following error, I think it's from `x-data` being on a `<form>` element:
`Uncaught DOMException: Failed to execute 'postMessage' on 'Window': HTMLInputElement object could not be cloned.`
![image](https://user-images.githubusercontent.com/15324232/131270265-6e87c92c-fadf-4c04-b718-eb4e3969c730.png)
![image](https://user-images.githubusercontent.com/15324232/131270469-d8f4f14e-4607-4222-858d-c0d7a0d2e18a.png)

When I moved my `x-data` from the form to a parent element the error went away & everything seems to work.

I assume if this is the case, it could be some sort of privacy reason with html forms. I'm ok with my workaround either way, feel free to close.

**Comment by HugoDF** [comment]
I'll have a look, thanks for reporting this issue.

**Comment by mattgrul** [comment]
I have encounterd this same error recently, it seems to be as above when the `x-data` is on the `form` tag AND you have an input field with the `name="id"`.

If you change the `name="id"` to anything other than id then the issue goes away....?
