### ISSUE TITLE
Alpine v3 Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tanthammar** [alpine-collective/alpinejs-devtools#295]
Devtools v1.1.0
Alpine 3.2.1
Livewire 2.5.5

I get this error a lot. Unable to use the plugin.

Here is an example when it breaks Alpine.
https://github.com/alpinejs/alpine/discussions/1952

```
Uncaught TypeError: Cannot read property '0' of undefined
    at AlpineDevtoolsBackend.getAlpineDataInstance (backend.js:236)
    at backend.js:355
    at Array.forEach (<anonymous>)
    at AlpineDevtoolsBackend.watchComponents (backend.js:354)
    at MutationObserver.<anonymous> (backend.js:497)
getAlpineDataInstance @ backend.js:236
(anonymous) @ backend.js:355
watchComponents @ backend.js:354
(anonymous) @ backend.js:497
```
![image](https://user-images.githubusercontent.com/21239634/131684023-1842d746-d1f7-4a6b-82a3-05202c38b0b0.png)

**Comment by tanthammar** [comment]
Duplicate #289

**Comment by HugoDF** [comment]
@tanthammar I'm not able to reproduce in the simulator for devtools but will release something that should avoid the devtools crashing noisily
