### ISSUE TITLE
Chrome / Black theme dev tools 

### ISSUE THREAD

**Issue by RajcsanyiZ** [alpine-collective/alpinejs-devtools#54]
When I scroll down the Alpine.js in devtool The background will be black. Of course I user black themed devtools. 

![image](https://user-images.githubusercontent.com/1152691/99182476-771be980-2735-11eb-99cc-64153f1b4d57.png)

After I refreshed it, the components and the data can't selectable.
![image](https://user-images.githubusercontent.com/1152691/99182551-d548cc80-2735-11eb-839e-112243f9b1dc.png)

I need to refresh the page, after I need to refresh Alpine.js devtool to work again it.

But the theme is again failed with the black background:
![image](https://user-images.githubusercontent.com/1152691/99182630-4d16f700-2736-11eb-83a0-dab690f8f441.png)

Maybe this problem is same that  #1

**Comment by HugoDF** [comment]
When you're able to upgrade to 0.0.4 let me know if it solves the issue (currently pending review on Chrome web store).

**Comment by HugoDF** [comment]
Closing this, feel free to re-open if it's still happening on latest.
