### ISSUE TITLE
Loading state for panel.html

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#61]
When opening the devtools for the first time there's a flash of unstyled content.

It's probably something we can deal with with `x-cloak` + a "Loading..." message that gets hidden on Alpine.js bootstrap.

cc @stephenoldham might have an idea of how to tackle this.

See the following gif:
![Kapture 2020-11-22 at 14 30 41](https://user-images.githubusercontent.com/6459679/99906498-73f1a200-2ccf-11eb-9f3b-ba7042c46037.gif)

**Comment by stephenoldham** [comment]
Yeah that needs some love. Can take a look 👍🏼

**Comment by HugoDF** [comment]
That would be great @stephenoldham 

I think the quickest win would be `x-cloak` on the panel component + a loading spinner/message with `x-show="false"` (so it disappears on Alpine load)

**Comment by ryangjchandler** [comment]
> That would be great @stephenoldham
> 
> I think the quickest win would be `x-cloak` on the panel component + a loading spinner/message with `x-show="false"` (so it disappears on Alpine load)

I think a Loading... message should be good enough. No need for spinners in my opinion :)

**Comment by stephenoldham** [comment]
Here's my thought. Simple pulsing logo. Hides with a `setTimeout` set here to 3 seconds. Better than a spinner and a bit of movement reassures the user something is actually happening. Thoughts?

![2020-11-23 11 54 35](https://user-images.githubusercontent.com/2156070/99959394-d8ba0480-2d82-11eb-93b5-f2103f8bcb7f.gif)

**Comment by HugoDF** [comment]
> Here's my thought. Simple pulsing logo. Hides with a `setTimeout` set here to 3 seconds. Better than a spinner and a bit of movement reassures the user something is actually happening. Thoughts?
> 
> ![2020-11-23 11 54 35](https://user-images.githubusercontent.com/2156070/99959394-d8ba0480-2d82-11eb-93b5-f2103f8bcb7f.gif)
> 

Nice one.

Maybe we put the logo in the same spot as the Alpine logo ends up? With "Alpine.js devtools loading" or similar (instead of the version text)?

I think having a "status line" type of thing will be useful eg. To say "devtools disconnected" or whatever we might add down the line.

**Comment by stephenoldham** [comment]
Right then, latest version:

<img src="https://user-images.githubusercontent.com/2156070/99966287-fe98d680-2d8d-11eb-80c1-9ce8fc8b68b5.gif" width="400" />

**Comment by ryangjchandler** [comment]
@stephenoldham Very nice!

**Comment by HugoDF** [comment]
I've noticed this ain't half as bad since #65 was fixed. Nice to have the "waiting for connection" state for potential future features

![Kapture 2020-11-23 at 20 15 15](https://user-images.githubusercontent.com/6459679/100011723-0c6c4d00-2dca-11eb-8554-758fccc7919b.gif)
