### ISSUE TITLE
Inject/load latest Alpine.js version

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#70]
Alpine.js "latest" version is hardcoded to "2.7.3", see https://github.com/alpine-collective/alpinejs-devtools/blob/master/packages/shell-chrome/src/state.js#L10

Couple of options to improve this

- keep the Alpine.js version that this project uses up to date and inject `require('./package.json').devDependencies.alpinejs` (we'll need to strip the semver range), or load a clean version from `package-lock`, `require('./package-lock.json').dependencies.alpinejs.version`
- load the latest Alpine.js version per the npm registry (it's a public endpoint), fetch `https://registry.npmjs.org/alpinejs`, get the `['dist-tags'].latest` field, sample request + extraction: `curl https://registry.npmjs.org/alpinejs | jq ".[\"dist-tags\"].latest"`

Key question to answer is:

- should we do this at build-time (using injection with rollup, similar to how we inject `__version__`)? or at runtime/extension startup (we would probably prefer the npm registry fetch approach in this case)?

Note: this is probably not super high priority, Alpine release cadence isn't very high.

**Update**: 

- We should fetch the version from `https://registry.npmjs.org/alpinejs`, if that fails fall back to a version injected from the package-lock.json.

- We need to update the way we compare versions, instead of `latest === version` we should do `isLaterSemverVersion(latest, version)` (semver would checks that major, minor and patch are greater than or equal to latest).

- When an "outdated" version is detected, the "Alpine version" text should be a link to https://github.com/alpinejs/alpine/releases

**Comment by ryangjchandler** [comment]
What is the version used for, showing whether your installed version is out of date?

**Comment by HugoDF** [comment]
> What is the version used for, showing whether your installed version is out of date?

Yep in the header

The more I think about it the more I think we should be fetching in the extension. Otherwise people on older versions of the extension will have inaccurate results.

**Comment by HugoDF** [comment]
For context, this is what it looks like when you're not on `2.7.3` at the moment

<img width="1264" alt="Screenshot 2020-11-25 at 12 29 38" src="https://user-images.githubusercontent.com/6459679/100228024-fa99bf80-2f19-11eb-98de-7445179b04f3.png">

**Comment by ryangjchandler** [comment]
Yeah, fetching the latest makes sense. Could probably use the NPM registry to do it.

For example, send a `fetch` to https://registry.npmjs.org/alpinejs and get the latest and use the `dist-tags.latest` value.

**Comment by HugoDF** [comment]
> Yeah, fetching the latest makes sense. Could probably use the NPM registry to do it.
> 
> For example, send a `fetch` to https://registry.npmjs.org/alpinejs and get the latest and use the `dist-tags.latest` value.

Yep got a simple curl working `curl https://registry.npmjs.org/alpinejs | jq ".[\"dist-tags\"].latest"` maybe we can fall back to the Alpine.js version per package-lock. This HTTP request might work well might work as our delay mechanism for "tools loading" state (instead of the arbitrary wait once components are loaded).

**Comment by HugoDF** [comment]
Also, we're currently doing an equality check for the version, maybe we should check that the version on the page is greater than or equal to the one loaded from npm/package-lock instead.

**Comment by ryangjchandler** [comment]
Yeah makes more sense to check gte/lte instead of equality.
