### ISSUE TITLE
Align code formatting

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#71]
Formatting is inconsistent across files.

- Add prettier with single quotes, 4 space, 120 width & apply it for HTML, CSS, JS and JSON files.
- Add formatting on pre-commut git hook
- Add check in GitHub actions (prettier -c) check.

**Comment by ryangjchandler** [comment]
Might be worth setting this up as an action too, I don't really like using Git hooks because I always forget about them 😶
