### ISSUE TITLE
Detect parent LiveView `name`

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#77]
When an Alpine.js component is detected inside of a LiveView view, use `view.name` as the name of the component.

**Comment by KevinBatdorf** [comment]
This could probably be added to #79 if you want to take over that PR

**Comment by HugoDF** [comment]
@KevinBatdorf was having a conversation with some LiveView peeps over on Twitter, I'll add the details I've gleaned here later

That PR is fine to go in without the changes for this issue 👍

**Comment by HugoDF** [comment]
Sample LiveView apps:

- https://github.com/pthompson/liveview_tailwind_modal, with the `$phx` magic property implemented, LiveView view.name is `$phx.view`
- [bernheisel.com](https://bernheisel.com/) has Alpine and LiveView, no `$phx` helper

Per [this tweet](https://twitter.com/bernheisel/status/1331424380468027393) we can do something like:

```js
const alpineElement = document.querySelector('[x-data]'); // some Alpine.js component root;
const phxEl = alpineElement.closest('[data-phx-view]');
if (phxEl) {
  const view = window.liveSocket.getViewByEl(phxEl);
  return view.name;
}
```

From a quick look, I think we could even use: `phxEl.dataset.phxView`
