### ISSUE TITLE
Circular structure bug when referencing the $el in a different variable

### ISSUE THREAD

**Issue by pomartel** [alpine-collective/alpinejs-devtools#78]
Referencing the $el in another object attribute will cause a bug when the devtool stringifies the object.

```javascript
var component = function() {
  return(
    {
      msg: 'Hello Alpine.js',
      init() {
        this.div = this.$el 
      }
    }
   )
}
```
See this page here with the console opened: https://cdpn.io/pomartel/debug/abmbyNg/xJAjOeOZonJk
The Codepen source here: https://codepen.io/pomartel/pen/abmbyNg

**Comment by HugoDF** [comment]
Solution here is probably to try to detect Alpine variables that are DOM Nodes and display "DOM Node" or "HTMLElement" instead of the actual value, a bit like we do for "function"

**Comment by pomartel** [comment]
Thanks for taking care of this guys. It almost works except when I wrap my `$el` in a jquery object like this `$($el)`. Sorry if I'm doing funny things with my Alpine setup! 😆

https://codepen.io/pomartel/pen/abmbyNg

**Comment by HugoDF** [comment]
@pomartel that's cause it's a jQuery instance 😂 I wonder how we can detect that

**Comment by pomartel** [comment]
I wonder if it's going to be possible to manage all the weird situations like this one. Maybe just wrap it in a try catch and display it as an "Unknown Element"?

**Comment by HugoDF** [comment]
I guess we can do `el instanceof jQuery || el instanceof $` but we'll need to check that `jQuery` or `$` exist 🤔 

The other way to do it is to try to unfurl the jQuery wrapper `property.get && property.get(0) instanceof HTMLElement` or `property[0] instanceof HTMLElement`

**Comment by HugoDF** [comment]
> I wonder if it's going to be possible to manage all the weird situations like this one. Maybe just wrap it in a try catch and display it as an "Unknown Element"?

the problem with this is that I think the error happens on `JSON.stringify`, so if we try/catch that, the whole component state will not be communicated to the devtools.

I think we can look at this again if we start sending data more piecemeal (eg. send components, send a component's top-level fields, send field values instead of 1 massive message that has everything in it)

**Comment by HugoDF** [comment]
@pomartel let's move the discussion to #101 I've got something working that will avoid the crash with jQuery values and with elements inside of arrays/objects (#96 )

**Comment by HugoDF** [comment]
Here's what the UI looks like btw, should be good enough for now, I get that having the devtools crash is probably the top priority.

![Uploading Screenshot 2020-12-03 at 15.22.01.png…]()
